# -*- coding: utf-8 -*-
"""automate_Jekiwantaufik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126jFdHChoxse7Zc05_I3kBwwUba6rQyD
"""

import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


def load_data():
    df = pd.read_csv("telco-customer-churn_raw/telco-customer-churn.csv")
    return df


def preprocess_data(df):

    df = df.drop(columns=["customerID"])

    df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
    df["TotalCharges"] = df["TotalCharges"].fillna(df["TotalCharges"].median())

    df = df.drop_duplicates()

    df["Churn"] = df["Churn"].map({"No": 0, "Yes": 1})

    categorical_cols = df.select_dtypes(include="object").columns
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

    return df


def save_preprocessed_data(df):

    os.makedirs("preprocessing", exist_ok=True)

    df.to_csv(
        "telco-customer-churn_preprocessing.csv",
        index=False
    )


def split_data(df):

    X = df.drop("Churn", axis=1)
    y = df["Churn"]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    return train_test_split(
        X_scaled,
        y,
        test_size=0.2,
        random_state=42
    )


def main():

    df = load_data()
    df_processed = preprocess_data(df)
    save_preprocessed_data(df_processed)

    X_train, X_test, y_train, y_test = split_data(df_processed)

    print("Train shape:", X_train.shape)
    print("Test shape:", X_test.shape)


if __name__ == "__main__":
    main()